format = """
[](color_0)\
$os\
[ ](bg:color_1 fg:color_0)\
$username\
$hostname\
$shell\
$shlvl\
[ ](fg:color_1)\
$directory\
$nix_shell\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

palette = 'base16'

[palettes.base16]
color_0 =  'red'
color_1 =  'yellow'
color_2 =  'green'
color_3 =  'cyan'
color_4 =  'blue'
color_5 =  'purple'
color_fg = 'bright-white'
# color_7 = 'bright-black'

[username]
style_user = "bg:color_1 fg:color_fg"
style_root = "bg:color_1 fg:color_fg"
format = '[$user]($style)'

[hostname]
style = "bg:color_1 fg:color_fg"
ssh_symbol = "@"
format = '[$ssh_symbol$hostname ]($style)'

[os]
disabled = false
style = "bg:color_0 fg:color_fg"

[os.symbols]
NixOS = "󱄅"
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Android = ""
Arch = "󰣇"
Artix = ""
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = ""
Pop = ""

[shlvl]
disabled = false
style = "bg:color_1 fg:color_fg"
format = '[\($shlvl\)]($style)'

[shell]
disabled = false
style = "bg:color_1 fg:color_fg"
format = '[$indicator]($style)'

[directory]
style = "blue"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[nix_shell]
format = '[$symbol(fg:white) $state( \($name\))]($style) '
symbol = "󱄅"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []
