format = """
[](color_0)\
$os\
[▓▒░](bg:color_1 fg:color_0)\
$username\
$hostname\
[▓▒░](bg:color_2 fg:color_1)\
$directory\
[▓▒░](bg:color_3 fg:color_2)\
$git_branch\
$git_state\
$git_status\
[▓▒░](bg:color_4 fg:color_3)\
$shell\
$shlvl\
$nix_shell\
$python\
[▓▒░](bg:color_5 fg:color_4)\
$cmd_duration\
[](fg:color_5)\
$battery\
$line_break\
$status\
$character
"""

add_newline = true

palette = "base16"

[palettes.base16]
color_0 = "red"
color_1 = "yellow"
color_2 = "green"
color_3 = "cyan"
color_4 = "blue"
color_5 = "purple"
color_fg = "bright-white"
color_muted = "black"

[username]
style_user = "bg:color_1 fg:color_muted"
style_root = "bg:color_1 fg:color_muted"
format = "[$user]($style)"

[hostname]
style = "bg:color_1 fg:color_muted"
ssh_symbol = "@"
format = "[$ssh_symbol$hostname]($style)"

[os]
disabled = false
style = "bg:color_0 fg:color_fg"
format = "[$symbol ]($style)"

[os.symbols]
NixOS = "󱄅"
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Android = ""
Arch = "󰣇"
Artix = ""
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = ""
Pop = ""

[directory]
style = "fg:color_muted bg:color_2"
before_repo_root_style = "fg:color_muted bg:color_2"
repo_root_style = "fg:color_muted bg:color_2 underline"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($repo_root_style)[$read_only]($read_only_style)"
truncation_length = 5
truncation_symbol = '…/'
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"
read_only = " "
read_only_style = "fg:color_muted bg:color_2"

[shlvl]
disabled = false
style = "bg:color_4 fg:color_fg"
format = "[\\($shlvl\\)]($style)"

[shell]
disabled = false
style = "bg:color_4 fg:color_fg"
format = "[$indicator]($style)"

[python]
format = "[$symbol $virtualenv]($style)"
symbol = "󰌠"
style = "fg:color_fg bg:color_4"
detect_extensions = []
detect_files = []

[nix_shell]
format = "[ $symbol $state( \\($name\\))]($style)"
symbol = "󱄅"
style = "fg:color_fg bg:color_4"
heuristic = true

[git_branch]
format = "[$symbol$branch]($style)"
symbol = " "
style = "fg:color_muted bg:color_3"

[git_status]
format = "[ $all_status$ahead_behind]($style)"
style = "fg:color_muted bg:color_3"

conflicted = ""
untracked = " "
modified = " "
staged = ""
renamed = " "
deleted = " "
stashed = "≡"

[git_state]
format = " \\([$state( $progress_current/$progress_total)]($style)\\)"
style = "fg:color_muted bg:color_3"

[cmd_duration]
format = "[$duration]($style)"
style = "fg:color_fg bg:color_5"

[battery]
format = "[ $symbol$percentage]($style)"

[[battery.display]]
threshold = 10

[status]
style = 'fg:color_fg'
format = '\([$status]($style)\)'
disabled = false

[character]
success_symbol = "[❯](fg:color_2)"
error_symbol = "[❯](fg:color_0)"
